### ISSUE TITLE
Error when performing 'make test'

### ISSUE THREAD

**Issue by twaddlac** [mitenjain/nanopore#7] opened 2015-04-17 15:48 UTC
Good day,

I am receiving an error when running 'make test.' I have all of the dependencies and it seems as though all the submodules compiled successfully.

Here's the info that I deem relevant to debugging from the testLog.txt output. Let me know if you need the rest of the file:

```
The job seems to have left a log file, indicating failure: /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job
Reporting file: /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/log.txt
log.txt:	---JOBTREE SLAVE OUTPUT LOG---
log.txt:	Parsed arguments and set up logging
log.txt:	Error in sample.int(x, size, replace, prob) : 
log.txt:	  too few positive probabilities
log.txt:	Calls: replicate ... trial_fn -> matrix -> table -> factor -> sample -> sample.int
log.txt:	Execution halted
log.txt:	Traceback (most recent call last):
log.txt:	  File "/opt/bioinformatics-software/minion-software/nanopore/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
log.txt:	    defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
log.txt:	  File "/opt/bioinformatics-software/minion-software/nanopore/submodules/jobTree/scriptTree/stack.py", line 153, in execute
log.txt:	    self.target.run()
log.txt:	  File "/opt/bioinformatics-software/minion-software/nanopore/nanopore/metaAnalyses/unmappedKmerAnalysis.py", line 51, in run
log.txt:	    system("Rscript nanopore/metaAnalyses/mappable_kmer_analysis.R {} {} {} {}".format(os.path.join(self.getLocalTempDir(), readType + "_kmer_counts.txt"), os.path.join(self.outputDir, readType + "_unmapped_kmer_counts.txt"), os.path.join(self.outputDir, readType + "_unmapped_top_bot_sigkmer_counts.txt"), os.path.join(self.outputDir, readType + "_volcano_plot.pdf")))
log.txt:	  File "/opt/bioinformatics-software/minion-software/nanopore/submodules/sonLib/bioio.py", line 184, in system
log.txt:	    raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
log.txt:	RuntimeError: Command: Rscript nanopore/metaAnalyses/mappable_kmer_analysis.R /tmp/tmpbeZ6rc/localTempDir/fake_readtype_kmer_counts.txt tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_unmapped_kmer_counts.txt tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_unmapped_top_bot_sigkmer_counts.txt tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_volcano_plot.pdf exited with non-zero status 1
log.txt:	Exiting the slave because of a failed job on host zoidberg
log.txt:	Due to failure we are reducing the remaining retry count of job /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job to 0
log.txt:	We have set the default memory of the failed job to 8589934592 bytes
Job: /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job is completely failed
Only failed jobs and their dependents (1 total) are remaining, so exiting.
Finished the main loop
Waiting for stats collator process to finish
Stats finished collating in 0.346755981445 seconds
Traceback (most recent call last):
  File "./nanopore/pipeline.py", line 214, in <module>
    main()
  File "/opt/bioinformatics-software/minion-software/nanopore/nanopore/pipeline.py", line 210, in main
    raise RuntimeError("Got failed jobs")
RuntimeError: Got failed jobs
```

**Comment by ifiddes** [comment] 2015-04-17 16:10
What version of R are you using?

Also, if it still exists on your system, what does the file

/tmp/tmpbeZ6rc/localTempDir/fake_readtype_kmer_counts.txt

Contain?

Thanks,

Ian Fiddes


On Friday, April 17, 2015, twaddlac <notifications@github.com> wrote:

> Good day,
>
> I am receiving an error when running 'make test.' I have all of the
> dependencies and it seems as though all the submodules compiled
> successfully.
>
> Here's the info that I deem relevant to debugging from the testLog.txt
> output. Let me know if you need the rest of the file:
>
> The job seems to have left a log file, indicating failure: /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job
> Reporting file: /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/log.txt
> log.txt:    ---JOBTREE SLAVE OUTPUT LOG---
> log.txt:    Parsed arguments and set up logging
> log.txt:    Error in sample.int(x, size, replace, prob) :
> log.txt:      too few positive probabilities
> log.txt:    Calls: replicate ... trial_fn -> matrix -> table -> factor -> sample -> sample.int
> log.txt:    Execution halted
> log.txt:    Traceback (most recent call last):
> log.txt:      File "/opt/bioinformatics-software/minion-software/nanopore/submodules/jobTree/src/jobTreeSlave.py", line 271, in main
> log.txt:        defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
> log.txt:      File "/opt/bioinformatics-software/minion-software/nanopore/submodules/jobTree/scriptTree/stack.py", line 153, in execute
> log.txt:        self.target.run()
> log.txt:      File "/opt/bioinformatics-software/minion-software/nanopore/nanopore/metaAnalyses/unmappedKmerAnalysis.py", line 51, in run
> log.txt:        system("Rscript nanopore/metaAnalyses/mappable_kmer_analysis.R {} {} {} {}".format(os.path.join(self.getLocalTempDir(), readType + "_kmer_counts.txt"), os.path.join(self.outputDir, readType + "_unmapped_kmer_counts.txt"), os.path.join(self.outputDir, readType + "_unmapped_top_bot_sigkmer_counts.txt"), os.path.join(self.outputDir, readType + "_volcano_plot.pdf")))
> log.txt:      File "/opt/bioinformatics-software/minion-software/nanopore/submodules/sonLib/bioio.py", line 184, in system
> log.txt:        raise RuntimeError("Command: %s exited with non-zero status %i" % (command, sts))
> log.txt:    RuntimeError: Command: Rscript nanopore/metaAnalyses/mappable_kmer_analysis.R /tmp/tmpbeZ6rc/localTempDir/fake_readtype_kmer_counts.txt tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_unmapped_kmer_counts.txt tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_unmapped_top_bot_sigkmer_counts.txt tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_volcano_plot.pdf exited with non-zero status 1
> log.txt:    Exiting the slave because of a failed job on host zoidberg
> log.txt:    Due to failure we are reducing the remaining retry count of job /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job to 0
> log.txt:    We have set the default memory of the failed job to 8589934592 bytes
> Job: /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job is completely failed
> Only failed jobs and their dependents (1 total) are remaining, so exiting.
> Finished the main loop
> Waiting for stats collator process to finish
> Stats finished collating in 0.346755981445 seconds
> Traceback (most recent call last):
>   File "./nanopore/pipeline.py", line 214, in <module>
>     main()
>   File "/opt/bioinformatics-software/minion-software/nanopore/nanopore/pipeline.py", line 210, in main
>     raise RuntimeError("Got failed jobs")
> RuntimeError: Got failed jobs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitenjain/nanopore/issues/7>.
>


-- 
Ian Fiddes

**Comment by twaddlac** [comment] 2015-04-17 16:45
Hi Ian,

I am using R version 3.1.3

That file isn't there and I haven't been able to recreate it.

On Fri, Apr 17, 2015 at 12:10 PM, Ian Fiddes <notifications@github.com>
wrote:

> What version of R are you using?
>
> Also, if it still exists on your system, what does the file
>
> /tmp/tmpbeZ6rc/localTempDir/fake_readtype_kmer_counts.txt
>
> Contain?
>
> Thanks,
>
> Ian Fiddes
>
>
> On Friday, April 17, 2015, twaddlac <notifications@github.com> wrote:
>
> > Good day,
> >
> > I am receiving an error when running 'make test.' I have all of the
> > dependencies and it seems as though all the submodules compiled
> > successfully.
> >
> > Here's the info that I deem relevant to debugging from the testLog.txt
> > output. Let me know if you need the rest of the file:
> >
> > The job seems to have left a log file, indicating failure:
> /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job
> > Reporting file:
> /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/log.txt
> > log.txt: ---JOBTREE SLAVE OUTPUT LOG---
> > log.txt: Parsed arguments and set up logging
> > log.txt: Error in sample.int(x, size, replace, prob) :
> > log.txt: too few positive probabilities
> > log.txt: Calls: replicate ... trial_fn -> matrix -> table -> factor ->
> sample -> sample.int
> > log.txt: Execution halted
> > log.txt: Traceback (most recent call last):
> > log.txt: File
> "/opt/bioinformatics-software/minion-software/nanopore/submodules/jobTree/src/jobTreeSlave.py",
> line 271, in main
> > log.txt: defaultMemory=defaultMemory, defaultCpu=defaultCpu, depth=depth)
> > log.txt: File
> "/opt/bioinformatics-software/minion-software/nanopore/submodules/jobTree/scriptTree/stack.py",
> line 153, in execute
> > log.txt: self.target.run()
> > log.txt: File
> "/opt/bioinformatics-software/minion-software/nanopore/nanopore/metaAnalyses/unmappedKmerAnalysis.py",
> line 51, in run
> > log.txt: system("Rscript nanopore/metaAnalyses/mappable_kmer_analysis.R
> {} {} {} {}".format(os.path.join(self.getLocalTempDir(), readType +
> "_kmer_counts.txt"), os.path.join(self.outputDir, readType +
> "_unmapped_kmer_counts.txt"), os.path.join(self.outputDir, readType +
> "_unmapped_top_bot_sigkmer_counts.txt"), os.path.join(self.outputDir,
> readType + "_volcano_plot.pdf")))
> > log.txt: File
> "/opt/bioinformatics-software/minion-software/nanopore/submodules/sonLib/bioio.py",
> line 184, in system
> > log.txt: raise RuntimeError("Command: %s exited with non-zero status %i"
> % (command, sts))
> > log.txt: RuntimeError: Command: Rscript
> nanopore/metaAnalyses/mappable_kmer_analysis.R
> /tmp/tmpbeZ6rc/localTempDir/fake_readtype_kmer_counts.txt
> tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_unmapped_kmer_counts.txt
> tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_unmapped_top_bot_sigkmer_counts.txt
> tests/output/metaAnalysis_UnmappedKmerAnalysis/fake_readtype_volcano_plot.pdf
> exited with non-zero status 1
> > log.txt: Exiting the slave because of a failed job on host zoidberg
> > log.txt: Due to failure we are reducing the remaining retry count of job
> /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job
> to 0
> > log.txt: We have set the default memory of the failed job to 8589934592
> bytes
> > Job:
> /opt/bioinformatics-software/minion-software/nanopore/testJobTree/jobs/t0/t0/job
> is completely failed
> > Only failed jobs and their dependents (1 total) are remaining, so
> exiting.
> > Finished the main loop
> > Waiting for stats collator process to finish
> > Stats finished collating in 0.346755981445 seconds
> > Traceback (most recent call last):
> > File "./nanopore/pipeline.py", line 214, in <module>
> > main()
> > File
> "/opt/bioinformatics-software/minion-software/nanopore/nanopore/pipeline.py",
> line 210, in main
> > raise RuntimeError("Got failed jobs")
> > RuntimeError: Got failed jobs
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/mitenjain/nanopore/issues/7>.
> >
>
>
> --
> Ian Fiddes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitenjain/nanopore/issues/7#issuecomment-94018027>.
>



-- 
Alan

**Comment by ifiddes** [comment] 2015-04-17 18:03
I have just pushed a fix for this I believe. The issue is with the test files not generating sufficient unmappable reads for the mappable/unmappable kmer analysis. Please let me know if it works.

However, we would like to point out that generally this version of the nanopore pipeline is deprecated and will not be maintained. The maintained version is called marginAlign and is available at https://github.com/benedictpaten/marginAlign

**Comment by twaddlac** [comment] 2015-04-20 16:39
Hi Ian,

The problem is fixed. Thank you for your help! I will use the marginAlign software from here on out, though.

**Closed** 2015-04-20 16:53 UTC
